config/routes.rb
Rails.application.routes.draw do
  resources :students
  root 'home#index'
  get 'home/about'
  get 'home/result'

  devise_for :admins
  resources :faculties
  
  # faculty  login and functionality
  get "faculty/login", to: "faculties#login"
  get "faculty/dashboard", to: "faculties#dashboard"
  post "faculty/is_login", to: "faculties#is_login"
  get "view/profile", to: "faculties#profile"
  get "add/assignment", to:"faculties#addassignment"
  get "faculty/signout", to: "faculties#signout"
  #student result handle here
  get "result/publish",to: "results#publish"
  get "result/check_marks",to:"results#check_marks"


  post "result/marksinsert", to: "results#marksinsert"
  post "result/assign",to: "results#assign"

  get "search/student", to: "faculties#search"
  get "student/details", to: "faculties#studentsdetails"
  post "faculty/students_details", to: "faculties#students_details"

  # Student login and functionality
  get "student/login", to: "students#login"
  get "student/dashboard", to: "students#dashboard"
  post "student/is_login", to: "students#is_login"

  get "student/signout", to: "students#signout"

  get "student/list", to:"faculties#list"
  get "student/assignment",to: "students#assignments"
  get "student/result", to:"students#resultsearch"
  get "student/result_details", to:"students#studentresult"
  post "student/result_details", to:"students#result_details"

  get "view/student/profile", to: "students#profile"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
	has_one_attached :studentimage, dependent: :destroy 
	has_one :result, dependent: :destroy
	validates :email_id,:roll_no ,uniqueness: true

	validates :first_name, :last_name ,:father_name, :password, :email_id, :password, :roll_no, :student_class,:studentimage,presence: true

	after_create :resultcreate, :rpcall
	#after student created result will be generate
		def resultcreate
			s = Student.last
			sn = s.roll_no
			sid = s.id
			r= Result.create(:student_roll=>sn,:student_id=>sid)
			r.save
		end

		def rpcall
			a = Admin.last
		    a.result_pub = false
		    a.save
		end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  def signout
    $stu = nil
    redirect_to student_login_path, notice:"Student logout successfully.."
  end

  def login

  end

  def studentresult
    respond_to do |format|
      format.html
      format.pdf do 
        render pdf: "file_name",template: "students/result_details.html.erb"
      end
    end
  end

  def dashboard
  end
  
#student login
  def is_login
    $stu = Student.find_by("email_id=? AND password=?", params[:email], params[:password])
    if $stu.present?
        redirect_to  student_dashboard_path, notice:"Student Login successfully.."
    else
        redirect_to student_login_path, notice:"Invalid Email or Password.."
    end
  end

#add here result database

  def result_details
    a = Admin.last
    rp = a.result_pub
    if rp == true
      (
      $res  = Result.find_by("student_roll=?", params[:rollno])
      $sname =Student.find_by("roll_no=?", params[:rollno])

      if $res.present?
        respond_to do |format|
          format.html
          format.pdf do 
            render pdf: "file_name",template: "students/result_details.html.erb"
          end
        end
      else
          redirect_to student_result_path , notice:"Incorrect Roll Number"
      end
      )
    else
          redirect_to student_dashboard_path, notice:"Result not published yet.."
    end
  end



  # GET /students/1 or /students/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do 
        render pdf: "file_name",template: "students/show.html.erb"
        # render pdf: "file_name",template: "students/result_details.html.erb"
      end
    end
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :father_name, :roll_no, :email_id, :student_class, :password, :mobile, :student_id, :studentimage)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: @student ) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name , class:"form-control", placeholder:"Last Name"%>
  </div>

  <div class="field form-group">
    <%= form.label :father_name %>
    <%= form.text_field :father_name, class:"form-control", placeholder:"Father Name" %>
  </div>


  <div class="field form-group">
    <%= form.label :email_id %>
    <%= form.text_field :email_id, class:"form-control", placeholder:"Email-Id" %>
  </div>


  <div class="field form-group">
    <%= form.label :password %>
    <%= form.text_field :password , class:"form-control", placeholder:"Password"%>
  </div>

  <div class="field form-group">
    <%= form.label :mobile %>
    <%= form.text_field :mobile , class:"form-control", placeholder:"Mobile"%>
  </div>

  <% if admin_signed_in? %>
  <div class="field form-group">
    <%= form.label :roll_no %>
    <%= form.text_field :roll_no, class:"form-control", placeholder:"Roll No." %>
  </div>
  <div class="field form-group">
    <%= form.label :student_class %>
    <%= form.text_field :student_class, class:"form-control", placeholder:"Class" %>
  </div>
  
  <div class="field form-group">
    <%= form.label :student_image %>
    <%= form.file_field :studentimage, class:"form-control" %>
  </div>

  <br>
  <div class="actions">
    <%= form.submit "Register",class:"btn btn-dark"%>
  </div>
  <% else %>
    <div class="actions">
      <%= form.submit "Update",class:"btn btn-dark"%>
    </div>
  <% end %>

<% end %>

app/views/students/assignments.html.erb
<!DOCTYPE html>
<div id="fixfooter">
<h1 align="center" style="color:red">Assignments</h1>
<br>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<% amt1,amt2,amt3,amt4,amt5 = Assignment.first,Assignment.second,Assignment.third,Assignment.fourth,Assignment.fifth %>

<div align="center" class="tab">
  <button class="tablinks" onclick="openCity(event, 'Hindi')">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hindi Assignments&nbsp;</button>
  <button class="tablinks" onclick="openCity(event, 'English')">English Assignments&nbsp;</button>
  <button class="tablinks" onclick="openCity(event, 'Maths')">Maths Assignments&nbsp;</button>
  <button class="tablinks" onclick="openCity(event, 'Science')">Science Assignments&nbsp;</button>
  <button class="tablinks" onclick="openCity(event, 'Social-Science')">&nbsp;Social-Science Assignments</button>
</div>

<div id="Hindi" class="tabcontent">
  <br>
  <h3 align="center">Hindi Assignments</h3><br><hr>
    <h3><pre><%= amt1.hindi %></pre></h3><hr>
    <br>
</div>

<div id="English" class="tabcontent">
  <br>
  <h3 align="center">English Assignments</h3><br><hr>
    <h3><pre><%= amt1.english %></pre></h3><hr>
</div>

<div id="Maths" class="tabcontent">
  <br>
  <h3 align="center">Maths Assignments</h3><br><hr>
    <h3><pre><%= amt1.maths %></pre></h3><hr>
</div>

<div id="Science" class="tabcontent">
  <br>
  <h3 align="center">Science Assignments</h3><br><hr>
    <h3><pre><%= amt1.science %></pre></h3><hr>
</div>

<div id="Social-Science" class="tabcontent">
  <br>
  <h3 align="center">Social-Science Assignments</h3><br><hr>
    <h3><pre><%= amt1.social_science %></pre></h3><br><hr>
</div>
</div>
<br>
<%= link_to 'Back', student_dashboard_path ,class:"btn btn-dark"%>
<br><br>
</body>
























<script>
function openCity(evt, cityName) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " active";
}
</script>
   
</body>
</html> 

app/views/students/dashboard.html.erb
<% if $stu.present? %>
<div id="admindashboard" style="border-style:inset;margin-top:55px;padding-right:2px;padding-left:2px;padding-bottom:120px;">
<table class="table">
  <thead class="thead-dark">
    <tr>
      </th>
      <th scope="col">
        <%= link_to 'View-Profile',view_student_profile_path,style:"font-size:21px;color:yellow;text-decoration: none;"%>
      </th>
      <th scope="col">
        <%= link_to 'Assignments',student_assignment_path,style: "font-size:21px;color:yellow;text-decoration: none;"  %>
      </th>
      <th scope="col">
        <%= link_to 'Search Result',student_result_path,style: "font-size:21px;color:yellow;text-decoration: none;"  %>
      </th>
      <th>
        <%= link_to 'Sign-out', student_signout_path ,style: "font-size:21px;color:yellow;text-decoration: none;" %>
      </th>
    </tr>
  </thead>
</table>
<br>
<div style="width:130px; height:auto;margin-left:20px">
  <%= image_tag($stu.studentimage,style:"padding-right:20px ;float:left;
      width:100%;") %>
</div>
<br>
<h5 style="color: blue";>Hello, <%= $stu.first_name %> <%=$stu.last_name%></h5>
<h4>Wel-come in Student Dashboard</h4>
<br>
<br>
</div>
<!-- notice for remaining fees -->
<marquee width="100%" direction="left" height="100%" scrollamount="10" bgcolor="black">
  <h5 style="color:yellow;">
    Important Notice :
    It is compulsory for all the students to pay the remaining fees before 15th July 
  </h5>
</marquee>
<br><br><br><br><br>


<% else %>
<div id="homepage">
      <br> <br><br><br>
      <h1 id="heading">Welcome in ERP portal</h1>
      <br><br>
      <h1 style="margin-left:130px;color:red;">Error,404</h1>
      <h2 style="margin-left:130px;color:red;">Page Not Found</h2>
</div>
<% end %>

app/views/students/destroy.js.erb
var element = document.getElementById("student<%= @student.id %>")
element.remove();

app/views/students/edit.html.erb
<h1>Update Details</h1>
<br>
<%= render 'form', student: @student %>
<br>

<% if admin_signed_in? %>

<%= link_to 'Show', @student ,class:"btn btn-secondary" %> |
<%= link_to 'Back', students_path ,class:"btn btn-dark"  %>
<% else %>
<%= link_to 'Back', view_student_profile_path %>
<% end %>

app/views/students/index.html.erb
<% if admin_signed_in? %>
<h1 align="center">Students</h1>
<br>
<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Father name</th>
      <th>Roll no</th>
      <th>Email</th>
      <th>Student class</th>
      <th>Password</th>
      <th>Mobile</th>
      <th>Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr id="student<%= student.id %>">
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.father_name %></td>
        <td><%= student.roll_no %></td>
        <td><%= student.email_id %></td>
        <td><%= student.student_class %></td>
        <td><%= student.password %></td>
        <td><%= student.mobile %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?',remote:true } %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
<br>

<%= link_to 'Register Student', new_student_path ,class:"btn btn-dark" %><br>
<br><br>
<%= link_to 'Back', root_path %>
<% else %>
<div id="homepage">
      <br> <br><br><br>
      <h1 id="heading">Welcome in ERP portal</h1>
      <br><br>
      <h1 style="margin-left:130px;color:red;">Error,404</h1>
      <h2 style="margin-left:130px;color:red;">Page Not Found</h2>
</div>
<% end %>

app/views/students/login.html.erb
<div id="loginpage" style="border-style:inset; padding:35px; margin-top: 25px;">
<h1 style="text-align:center;color:black;font-family:verdana;">Student Login</h1>

<div align="center"><%= image_tag("logo/student.png",width:"180px",height:"180px")%></div>
<%= form_with url:student_is_login_path do |form| %>
  	
  <div class="field form-group">
    <%= form.label :email %><br />
    <%= form.text_field :email, class:"form-control"%>
  </div>

  <div class="field form-group">
    <%= form.label :password %><br />
    <%= form.password_field :password, class:"form-control"%>
  </div>
  <br>

  <div class="actions">
    <%= form.submit "Log-in",class:"btn btn-dark"%>
  </div>
</div>
<br>
<br>
<%end%>

app/views/students/new.html.erb
<% if admin_signed_in? %>

<h1 align="center">Register Student</h1>
<br>
<%= render 'form', student: @student %>
<br>
<%= link_to 'Back', root_path ,class:"btn btn-secondary"%>
<br><br>
<br>
<% else %>
<div id="homepage">
      <br> <br><br><br>
      <h1 id="heading">Welcome in ERP portal</h1>
      <br><br>
      <h1 style="margin-left:130px;color:red;">Error,404</h1>
      <h2 style="margin-left:130px;color:red;">Page Not Found</h2>
</div>
<% end %>

app/views/students/profile.html.erb
<h1 align="center">View-Profile</h1>

<br>
<div class="jumbotron">
  <h1 style="margin-left:252px">
    <%= $stu.first_name %>
    <%= $stu.last_name %>
  </h1>

  <div style="width:250px; height:auto">
      <%= image_tag($stu.studentimage,style:"padding-right:20px ;float:left;
      width:100%;") %>
  </div>
  <p class="lead">
    <h5><strong>Father name:</strong> <%= $stu.father_name %></h5><br>
    <strong>Roll no:</strong> <%= $stu.roll_no %> |
    <strong>Class:</strong><%= $stu.student_class %>
  </p>

  <hr class="my-4">
    <p><strong>Email:</strong> <%= $stu.email_id %></p>
    <p><strong>Mobile:</strong> <%= $stu.mobile %></p>

  <%= link_to 'Update', edit_student_path($stu),class:"btn btn-secondary" %> |
  <%= link_to 'Back', student_dashboard_path ,class:"btn btn-dark"%>
  <br><br>
</div>

app/views/students/result_details.html.erb
<html>
<head>
<style>
table, th, td {
  border: 1px solid black;
  text-align:center;
}
table{
  border-collapse: collapse;
  width:70%;
}
</style>
</head>

<body>

<h1 align="center">Student Result</h1>

<p align="right"><%= link_to "Download Result",student_result_details_path(format: :pdf) %></p>

<p align="right"><%= link_to 'Back to Search',student_result_path %></p>

<br>
<!-- percent calculation -->
<% @per=$res.obtained_marks.to_f/5 %>
<% @hm= $res.hindi %>
<% @em=$res.english%>
<% @sm=$res.science%>
<% @ssm=$res.social_science %>
<% @mm=$res.maths %>


<div class="jumbotron">
<!-- student data -->
<h1 align="center" style="color:maroon;font-family:Trattatello, fantasy">Sunshine Public School</h1>
<br><br>
<div style="width:120px; height:auto">
    <%= image_tag($sname.studentimage,style:"float:left;
      width:100%;") %>
</div>

<h4 style="color:maroon" align="right">Name: <%= $sname.first_name %> <%= $sname.last_name %></h4>


<h4 style="color:maroon" align="right">Father Name: <%= $sname.father_name %></h4>
<h4 style="color:maroon" align="right">Roll Number: <%= $sname.roll_no %></h4>
<h4 style="color:maroon" align="right">Class: <%= $sname.student_class %></h4>

<% if (@em and @hm and @em and @sm and @ssm and @mm)!= nil %>
<div>
    <br>
    <br>
    <table align="center">
      <tr>
        <th>Subject Code</th>
        <th>Subject Name</th>
        <th>Minimum Marks</th>
        <th>Maximum Marks</th>
        <th>Marks Obtained</th>
        <th>Remarks</th>
      </tr>

      <tr>
        <td>S101</td>
        <td>Science</td>
        <td>33</td>
        <td>100</td>
        <td><%=@sm%></td>
        <td><%=$res.remark%></td>
      </tr>

      <tr>
        <td>H102</td>
        <td>Hindi</td>
        <td>33</td>
        <td>100</td>
        <td><%=@hm%></td>
        <td><%=$res.remark%></td>
      </tr>

      <tr>
        <td>E103</td>
        <td>English</td>
        <td>33</td>
        <td>100</td>
        <td><%=@em%></td>
        <td><%=$res.remark%></td>
      </tr>

      <tr>
        <td>S104</td>
        <td>Social-Science</td>
        <td>33</td>
        <td>100</td>
        <td><%=@ssm%></td>
        <td><%=$res.remark%></td>
      </tr>

      <tr>
        <td>M105</td>
        <td>Maths</td>
        <td>33</td>
        <td>100</td>
        <td><%=@mm%></td>
        <td><%=$res.remark%></td>
      </tr>

      <tr>
        <td></td>
        <td></td>
        <td><b>Total</b></td>
        <td style="color:blue";><b><%=$res.total%></b></td>
        <td style="color:blue";><b><%=$res.obtained_marks%></b></td>
        <td style="color:red";><b><%=$res.remark%></b></td>
      </tr>
    </table>
</div>

<% else %>
    <br>
    <h2>Result in Process..</h2>
<% end %>
<br>
<br><br><br>
<br>
<h4 style="color:black;margin-left:40px;">Result :</h4>
<h5 style="color:red;margin-left:60px;">You are <%=$res.remark%>ED!!</h5>
<br>
</div>
</body>
</html>

app/views/students/resultsearch.html.erb
<div id="fixfooter">
<h1 align="center">Search Result</h1>
<br>
<%= form_with url:student_result_details_path do |form| %>

	<div class="field form-group">
	    <%= form.text_field :rollno, class:"form-control",placeholder:"Enter Roll No."%>
	  </div>

	<div class="actions">
	    <%= form.submit "search",class:"btn btn-dark"%>
	  </div>

	  <br>
	  <br>
	  <%= link_to 'Back to Dashboard',student_dashboard_path %>
<%end%>
</div>

app/views/students/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @student.first_name %>
    <%= @student.last_name %>
  </h1>
    <div style="width:200px; height:auto">
      <%= image_tag(@student.studentimage,style:"padding-right:20px ;float:left;
      width:100%;") %>
    </div>
  <p class="lead">
    <h5><strong>Father name:</strong> <%= @student.father_name %></h5><br>
    <strong>Roll no:</strong> <%= @student.roll_no %> |
    <strong>Class:</strong><%= @student.student_class %>
  </p>

  <hr class="my-4">
    <br>
    <p><strong>Email:</strong> <%= @student.email_id %></p>
    <p><strong>Mobile:</strong> <%= @student.mobile %></p>

<% if admin_signed_in? && !$faculty.present? %>

  <%= link_to 'Edit', edit_student_path(@student),class:"btn btn-secondary"%> |
  <%= link_to 'Back', students_path ,class:"btn btn-dark"%>

<% else %>

  <% if $faculty.present? %>
    <br><br>
    <h2 align="center">Insert <%= $faculty.subject %> Marks</h2>
    <br><br>    

    <%=form_with url:result_marksinsert_path do |form| %>
      <label>Choose Your Subject:</label>
      <select name="subject">
        <option value="hindi">Hindi</option>
        <option value="english">English</option>
        <option value="maths">Maths</option>
        <option value="science">Science</option>
        <option value="social_science">Social-Science</option>
      </select>
      <br>

      <div class="field form-group">
        <%= form.number_field :marks, class:"form-control",placeholder:"Enter Marks",maxlength:"2"%>
      </div>
      <div class="field form-group">

        <%= form.hidden_field :s_id, value: @student.id %>
      </div>
      
      <div class="actions">
          <%= form.submit "Update-Marks",class:"btn btn-dark"%>
      </div>
    <%end%>
  <% end %>
<br>

    <%= link_to 'Back',student_list_path ,class:"btn btn-dark"%> 

<% end %>
</div>

app/views/students/studentresult.html.erb
<html>
<head>
<style>
table, th, td {
  border: 1px solid black;
  text-align:center;
}
table{
 border-collapse: collapse;
}
</style>
</head>

<body>

<h1 align="center">Student Result</h1>

<p align="right"><%= link_to "Download Result",student_result_details_path(format: :pdf) %></p>

<p align="right"><%= link_to 'Back to Search',student_result_path %></p>

<br>
<!-- percent calculation -->
<% @per=$res.obtained_marks.to_f/5 %>
<% @hm= $res.hindi %>
<% @em=$res.english%>
<% @sm=$res.science%>
<% @ssm=$res.social_science %>
<% @mm=$res.maths %>





<div class="jumbotron">
<!-- student data -->
<h1 align="center" style="color:maroon;font-family:Trattatello, fantasy">Sunshine Public School</h1>
<br><br>
<div style="width:120px; height:auto">
    <%= image_tag($sname.studentimage,style:"float:left;
      width:100%;") %>
</div>

<h5 style="color:maroon" align="right">Name: <%= $sname.first_name %> <%= $sname.last_name %></h5>


<h5 style="color:maroon" align="right">Father Name: <%= $sname.father_name %></h5>
<h5 style="color:maroon" align="right">Roll Number: <%= $sname.roll_no %></h5>
<h5 style="color:maroon" align="right">Class: <%= $sname.student_class %></h5>

<% if (@em and @hm and @em and @sm and @ssm and @mm)!= nil %>
<div>
    <br>
    <br>
    <table align="center">
      <tr>
        <th>Subject Code</th>
        <th>Subject Name</th>
        <th>Minimum Marks</th>
        <th>Maximum Marks</th>
        <th>Marks Obtained</th>
        <th>Remarks</th>
      </tr>

      <tr>
        <td>S101</td>
        <td>Science</td>
        <td>33</td>
        <td>100</td>
        <td><%=@sm%></td>
        <td><%=$res.remark%></td>
      </tr>

      <tr>
        <td>H102</td>
        <td>Hindi</td>
        <td>33</td>
        <td>100</td>
        <td><%=@hm%></td>
        <td><%=$res.remark%></td>
      </tr>

      <tr>
        <td>E103</td>
        <td>English</td>
        <td>33</td>
        <td>100</td>
        <td><%=@em%></td>
        <td><%=$res.remark%></td>
      </tr>

      <tr>
        <td>S104</td>
        <td>Social-Science</td>
        <td>33</td>
        <td>100</td>
        <td><%=@ssm%></td>
        <td><%=$res.remark%></td>
      </tr>

      <tr>
        <td>M105</td>
        <td>Maths</td>
        <td>33</td>
        <td>100</td>
        <td><%=@mm%></td>
        <td><%=$res.remark%></td>
      </tr>

      <tr>
        <td></td>
        <td></td>
        <td><b>Total</b></td>
        <td style="color:blue";><b><%=$res.total%></b></td>
        <td style="color:blue";><b><%=$res.obtained_marks%></b></td>
        <td style="color:red";><b><%=$res.remark%></b></td>
      </tr>
    </table>
</div>
<% else %>
    <br>
    <h2>Result in Process..</h2>
<% end %>
<br>
<br><br><br>
<br>
<h4 style="color:black;margin-left:40px;">Result :</h4>
<h5 style="color:red;margin-left:60px;">You are <%=$res.remark%>ED!!</h5>
<br>
</div>
</body>
</html>