config/routes.rb
Rails.application.routes.draw do
  resources :students
  root 'home#index'
  get 'home/about'
  get 'home/result'

  devise_for :admins
  resources :faculties
  
  # faculty  login and functionality
  get "faculty/login", to: "faculties#login"
  get "faculty/dashboard", to: "faculties#dashboard"
  post "faculty/is_login", to: "faculties#is_login"
  get "view/profile", to: "faculties#profile"
  get "add/assignment", to:"faculties#addassignment"
  get "faculty/signout", to: "faculties#signout"
  #student result handle here
  get "result/publish",to: "results#publish"
  get "result/check_marks",to:"results#check_marks"


  post "result/marksinsert", to: "results#marksinsert"
  post "result/assign",to: "results#assign"

  get "search/student", to: "faculties#search"
  get "student/details", to: "faculties#studentsdetails"
  post "faculty/students_details", to: "faculties#students_details"

  # Student login and functionality
  get "student/login", to: "students#login"
  get "student/dashboard", to: "students#dashboard"
  post "student/is_login", to: "students#is_login"

  get "student/signout", to: "students#signout"

  get "student/list", to:"faculties#list"
  get "student/assignment",to: "students#assignments"
  get "student/result", to:"students#resultsearch"
  get "student/result_details", to:"students#studentresult"
  post "student/result_details", to:"students#result_details"

  get "view/student/profile", to: "students#profile"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/faculty.rb
class Faculty < ApplicationRecord
	validates :email,:password, presence:true
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :set_faculty, only: %i[ show edit update destroy ]

  # GET /faculties or /faculties.json
  def index
    @faculties = Faculty.all
  end
  
  def list
    @sdetail = Student.all
  end
  
  def login

  end


  def signout
    $faculty = nil
    redirect_to faculty_login_path, notice:"Faculty logout successfully.."
  end

  def dashboard
  end
  
#checking data
  def is_login
    $faculty = Faculty.find_by("email=? AND password=?", params[:email], params[:password])

    if $faculty.present?
        redirect_to faculty_dashboard_path, notice: "Faculty Logged in successfully.."
    else
        redirect_to faculty_login_path, notice: "Invalid Email or password.."
    end
  end

  def students_details
    $studentdetails = Student.find_by("roll_no=?", params[:rollno])

    if $studentdetails.present?
        redirect_to student_details_path, notice: "Students Details founded.."
    else
        redirect_to search_student_path, notice: "Student Details Not founded.."
    end
  end
   
  # GET /faculties/1 or /faculties/1.json
  def show
  end

  # GET /faculties/new
  def new
    @faculty = Faculty.new
  end

  # GET /faculties/1/edit
  def edit
  end

  # POST /faculties or /faculties.json
  def create
    @faculty = Faculty.new(faculty_params)

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to @faculty, notice: "Faculty was successfully created." }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculties/1 or /faculties/1.json
  def update
    respond_to do |format|
      if @faculty.update(faculty_params)
        format.html { redirect_to @faculty, notice: "Faculty was successfully updated." }
        format.json { render :show, status: :ok, location: @faculty }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1 or /faculties/1.json
  def destroy
    @faculty.destroy
    respond_to do |format|
      format.html { redirect_to faculties_url, notice: "Faculty was successfully destroyed." }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculty
      @faculty = Faculty.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def faculty_params
      params.require(:faculty).permit(:first_name, :last_name, :email, :mobile, :subject, :subject_code,:password,:faculty_id)
    end
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/views/faculties/_form.html.erb
<%= form_with(model: @faculty) do |form| %>
  <% if faculty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(faculty.errors.count, "error") %> prohibited this faculty from being saved:</h2>

      <ul>
        <% faculty.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name"%>
  </div>

  <div class="field form-group">
    <%= form.text_field :last_name, class:"form-control",placeholder:"Last Name"%>
  </div>

  <div class="field form-group">
    <%= form.text_field :email, class:"form-control",placeholder:"Email-Id"%>
  </div>

  <div class="field form-group">
    <%= form.text_field :mobile, class:"form-control",placeholder:"Mobile No."%>
  </div>

  <div class="field form-group">
    <%= form.text_field :subject, class:"form-control",placeholder:"Subject" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :password, class:"form-control" ,placeholder:"Password"%>
  </div>

  <div class="field form-group">
    <%= form.text_field :subject_code, class:"form-control" ,placeholder:"Subject Code"%>
  </div>

  <% if admin_signed_in? %>

  <div class="field form-group">
    <%= form.text_field :faculty_id, class:"form-control" ,placeholder:"Faculty Id"%>
  </div>
  
  <div class="actions">
    <%= form.submit "Register",class:"btn btn-dark"%>
  </div>

  <% else %>
    <div class="actions">
      <%= form.submit "Update",class:"btn btn-dark"%>
    </div>

  <% end %>
  
<% end %>

app/views/faculties/addassignment.html.erb
<% if $faculty.present? %>
	<h1 align="center">Add Assignments</h1>
	<br>
	<br>
	<%=form_with url:result_assign_path do |form| %>

		<strong><label>Select Your Subject: </label></strong>
		      <select name="subjects">
		        <option value="hindi">Hindi</option>
		        <option value="english">English</option>
		        <option value="maths">Maths</option>
		        <option value="science">Science</option>
		        <option value="social_science">Social-Science</option>
		      </select>&nbsp;&nbsp;

		<strong><label>Select Assignment No.: </label></strong>
		      <select name="a_num">
		        <option value=1>01</option>
		        <option value=2>02</option>
		        <option value=3>03</option>
		        <option value=4>04</option>
		        <option value=5>05</option>
		      </select>
<br>
		  </br>
	      <div class="field form-group">
	        <%= form.text_area :stu_assignments, class:"form-control",placeholder:"Enter Your Questions",rows:"10",cols:"80"%>
	      </div>
	      
	      <div class="actions">
	          <%= form.submit "Add Assignment",class:"btn btn-dark"%>
	      </div>
	    <%end%>
	    <br>
	<%= link_to 'Back to Dashboard',faculty_dashboard_path %>
<br><br>

<% else %>
<div id="homepage">
      <br> <br><br><br>
      <h1 id="heading">Welcome in ERP portal</h1>
      <br><br>
      <h1 style="margin-left:130px;color:red;">Error,404</h1>
      <h2 style="margin-left:130px;color:red;">Page Not Found</h2>
</div>
<% end %>

app/views/faculties/dashboard.html.erb
<% if $faculty.present? %>
<div id="admindashboard" style="border-style:inset;margin-top:55px;padding-right:2px;padding-left:2px;padding-bottom:120px;">
	<table class="table">
		<thead class="thead-dark">
			<tr>
				</th>
				<th scope="col">
					<%= link_to 'View-Profile',view_profile_path,style:"font-size:21px;color:#FFFFFF;text-decoration: none;"%>
				</th>
				<th scope="col">
					<%= link_to 'Search Students',search_student_path,style: "font-size:21px;color:#FFFFFF;text-decoration: none;"  %>
				</th>
				<th scope="col">
					<%= link_to 'Show all',student_list_path ,style: "font-size:21px;color:#FFFFFF;text-decoration: none;" %>
				</th>
				<th scope="col">
					<%= link_to 'Add Assignment',add_assignment_path ,style: "font-size:21px;color:#FFFFFF;text-decoration: none;" %>
				</th>
				<th scope="col">
					<%= link_to 'Sign-out', faculty_signout_path ,style: "font-size:21px;color:#FFFFFF;text-decoration: none;" %>
				</th>
			</tr>
		</thead>
	</table>

	<br><br>
	<h5 style="color: red;margin-left:40px;">Hello, <%= $faculty.first_name %> <%= $faculty.last_name %></h5>
	<h4 style="margin-left:40px;">Wel-come in Faculty Dashboard</h4>
	<br>
	<br>

</div>
	<!-- notice for remaining fees -->
	<marquee width="100%" direction="left" height="100%" scrollamount="10" bgcolor="black">
	  <h5 style="color:white;">
	    Important Notice :
	    We are organising the third Convention for Higher Education at University College on 13th september
	  </h5>
	</marquee>
	<br><br><br><br><br>
<% else %>
<div id="homepage">
      <br> <br><br><br>
      <h1 id="heading">Welcome in ERP portal</h1>
      <br><br>
      <h1 style="margin-left:130px;color:red;">Error,404</h1>
      <h2 style="margin-left:130px;color:red;">Page Not Found</h2>
</div>
<% end %>

app/views/faculties/destroy.js.erb
var element = document.getElementById("faculty<%= @faculty.id %>")
element.remove();

app/views/faculties/edit.html.erb
<h1>Update Details</h1>
<br>
<%= render 'form', faculty: @faculty %>
<br>

<% if admin_signed_in? %>

<%= link_to 'Show', @faculty ,class:"btn btn-secondary" %> |
<%= link_to 'Back', faculties_path ,class:"btn btn-dark"%>
<% else %>
<%= link_to 'Back', view_profile_path %>
<% end %>

app/views/faculties/index.html.erb
<% if admin_signed_in? %>

<h1 align="center">Faculties</h1><br>
  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Mobile</th>
        <th>Subject</th>
        <th>Subject code</th>
        <th>Password</th>
        <th>Faculty Id</th>
        <th>Actions</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @faculties.each do |faculty| %>
        <tr id="faculty<%= faculty.id %>">
          <td><%= faculty.first_name %></td>
          <td><%= faculty.last_name %></td>
          <td><%= faculty.email %></td>
          <td><%= faculty.mobile %></td>
          <td><%= faculty.subject %></td>
          <td><%= faculty.subject_code %></td>
          <td><%= faculty.password %></td>
          <td><%= faculty.faculty_id%></td>
          <td><%= link_to 'View', faculty %></td>
          <td><%= link_to 'Update', edit_faculty_path(faculty) %></td>
          <td><%= link_to 'Remove', faculty, method: :delete, data: { confirm: 'Are you sure?',remote:true} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>

  <%= link_to 'Register New Faculty', new_faculty_path ,class:"btn btn-dark"%><br>
  <br><br>
  <%= link_to 'Back', root_path %>
<% else %>
<div id="homepage">
      <br> <br><br><br>
      <h1 id="heading">Welcome in ERP portal</h1>
      <br><br>
      <h1 style="margin-left:130px;color:red;">Error,404</h1>
      <h2 style="margin-left:130px;color:red;">Page Not Found</h2>
</div>
<% end %>

app/views/faculties/list.html.erb
<% if $faculty.present? %>
<div id="fixfooter">
<br>
<h1 align="center">Students-List</h1>
<br>
<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Father name</th>
      <th>Roll no</th>
      <th>Email</th>
      <th>Student class</th>
      <th>Mobile</th>
      <th>Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @sdetail.each do |student| %>
      <tr>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.father_name %></td>
        <td><%= student.roll_no %></td>
        <td><%= student.email_id %></td>
        <td><%= student.student_class %></td>
        <td><%= student.mobile %></td>
        <td><%= link_to 'Insert-Marks', student %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br><br><br><br>
<%= link_to 'Back to Dashboard',faculty_dashboard_path %>
<br><br>
</div>

<% else %>
<div id="homepage">
      <br> <br><br><br>
      <h1 id="heading">Welcome in ERP portal</h1>
      <br><br>
      <h1 style="margin-left:130px;color:red;">Error,404</h1>
      <h2 style="margin-left:130px;color:red;">Page Not Found</h2>
</div>
<% end %>

app/views/faculties/login.html.erb
<div id="loginpage" style="border-style:inset; padding:35px; margin-top: 25px;">

<h1 style="text-align:center;color:black;font-family:verdana;">Faculty Login</h1>


<div align="center"><%= image_tag("logo/faculty.png",width:"180px",height:"180px")%></div>
<%= form_with url:faculty_is_login_path do |form| %>
  	
  <div class="field form-group">
    <%= form.label :email %><br />
    <%= form.text_field :email, class:"form-control"%>
  </div>

  <div class="field form-group">
    <%= form.label :password %><br />
    <%= form.password_field :password, class:"form-control"%>
  </div>
  <br>

  <div class="actions">
    <%= form.submit "Log-in",class:"btn btn-dark"%>
  </div>

<br>
</div>

<%end%>

app/views/faculties/new.html.erb
<% if admin_signed_in? %>

<h1 align="center">Register Faculty</h1>
<br>

<%= render 'form', faculty: @faculty %>
<br>
<%= link_to 'Back', root_path ,class:"btn btn-secondary" %>
<br><br><br><br>
<% else %>
<div id="homepage">
      <br> <br><br><br>
      <h1 id="heading">Welcome in ERP portal</h1>
      <br><br>
      <h1 style="margin-left:130px;color:red;">Error,404</h1>
      <h2 style="margin-left:130px;color:red;">Page Not Found</h2>
</div>
<% end %>

app/views/faculties/profile.html.erb
<% if $faculty.present? %>
  <h1 align="center">View-Profile</h1>
  <br>

  <div class="jumbotron">
    <h2>
      <%= $faculty.first_name %>
      <%= $faculty.last_name %>
    </h2>
    <p class="lead">
      <strong>Email:</strong> <%= $faculty.email %> |
      <strong>Mobile:</strong> <%= $faculty.mobile %>
    </p>
    <hr class="my-4">
    <p><strong>Subject:</strong><%= $faculty.subject %></p>
    <p><strong>Subject code:</strong><%= $faculty.subject_code %></p>
    <%= link_to 'Update', edit_faculty_path($faculty),class:"btn btn-secondary" %> |
    <%= link_to 'Back', faculty_dashboard_path ,class:"btn btn-dark"%>
  </div>

<% else %>
<div id="homepage">
      <br> <br><br><br>
      <h1 id="heading">Welcome in ERP portal</h1>
      <br><br>
      <h1 style="margin-left:130px;color:red;">Error,404</h1>
      <h2 style="margin-left:130px;color:red;">Page Not Found</h2>
</div>
<% end %>

app/views/faculties/search.html.erb
<% if $faculty.present? %>
<div id="fixfooter">
	<br>
	<h1>Search Students Details</h1>
	<br>
	<%= form_with url:faculty_students_details_path do |form| %>

		<div class="field form-group">
		    <%= form.text_field :rollno, class:"form-control",placeholder:"Enter Roll No."%>
		  </div>

		<div class="actions">
		    <%= form.submit "search",class:"btn btn-dark"%>
		  </div>

		  <br>
		  <br>
		  <%= link_to 'Back to Dashboard',faculty_dashboard_path %>
	<%end%>
</div>	
<% else %>
<div id="homepage">
      <br> <br><br><br>
      <h1 id="heading">Welcome in ERP portal</h1>
      <br><br>
      <h1 style="margin-left:130px;color:red;">Error,404</h1>
      <h2 style="margin-left:130px;color:red;">Page Not Found</h2>
</div>
<% end %>

app/views/faculties/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @faculty.first_name %>
    <%= @faculty.last_name %>
  </h1>
  <p class="lead">
    <strong>Email:</strong> <%= @faculty.email %> |
    <strong>Mobile:</strong> <%= @faculty.mobile %>
  </p>
  <hr class="my-4">
  <p><strong>Subject:</strong><%= @faculty.subject %></p>
  <p><strong>Subject code:</strong><%= @faculty.subject_code %></p>
  <%= link_to 'Edit', edit_faculty_path(@faculty),class:"btn btn-secondary" %> |
  <% if admin_signed_in? %>
  <%= link_to 'Back',faculties_path ,class:"btn btn-dark"%>
  <% else %>
  <%= link_to 'Back',faculty_dashboard_path,class:"btn btn-dark"%>
  <% end %>
</div>

app/views/faculties/studentsdetails.html.erb
<% if $faculty.present? %>
<div id="fixfooter">
<br>
<h1 align="center">
	Student Details
</h1>
<br>
<div style="background-color: #99CCFF;" >
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Roll No.</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Father Name</th>
      <th scope="col">Email</th>
      <th scope="col">Class</th>
      <th scope="col">Mobile No.</th>
    </tr>
  </thead>
  <tbody>
  	<br>
    <tr>
      <td><%= $studentdetails.roll_no %></td>
      <td><%= $studentdetails.first_name %></td>
      <td><%= $studentdetails.last_name %></td>
      <td><%= $studentdetails.father_name %></td>
      <td><%= $studentdetails.email_id %></td>
      <td><%= $studentdetails.student_class %></td>
      <td><%= $studentdetails.mobile %></td>
    </tr>
  </tbody>
</table>
</div>
<hr>
<%= link_to 'Back',:back, class:'btn btn-dark'%>
</div>
<br><br><br>
<% else %>
<div id="homepage">
      <br> <br><br><br>
      <h1 id="heading">Welcome in ERP portal</h1>
      <br><br>
      <h1 style="margin-left:130px;color:red;">Error,404</h1>
      <h2 style="margin-left:130px;color:red;">Page Not Found</h2>
</div>
<% end %>