config/routes.rb
Rails.application.routes.draw do
  resources :students
  root 'home#index'
  get 'home/about'
  get 'home/result'

  devise_for :admins
  resources :faculties
  
  # faculty  login and functionality
  get "faculty/login", to: "faculties#login"
  get "faculty/dashboard", to: "faculties#dashboard"
  post "faculty/is_login", to: "faculties#is_login"
  get "view/profile", to: "faculties#profile"
  get "add/assignment", to:"faculties#addassignment"
  get "faculty/signout", to: "faculties#signout"
  #student result handle here
  get "result/publish",to: "results#publish"
  get "result/check_marks",to:"results#check_marks"


  post "result/marksinsert", to: "results#marksinsert"
  post "result/assign",to: "results#assign"

  get "search/student", to: "faculties#search"
  get "student/details", to: "faculties#studentsdetails"
  post "faculty/students_details", to: "faculties#students_details"

  # Student login and functionality
  get "student/login", to: "students#login"
  get "student/dashboard", to: "students#dashboard"
  post "student/is_login", to: "students#is_login"

  get "student/signout", to: "students#signout"

  get "student/list", to:"faculties#list"
  get "student/assignment",to: "students#assignments"
  get "student/result", to:"students#resultsearch"
  get "student/result_details", to:"students#studentresult"
  post "student/result_details", to:"students#result_details"

  get "view/student/profile", to: "students#profile"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def result
    @result = Result.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<div id="footer">
	<br>
	<h4 style="margin-top:5px;margin-left:645px;font-family: Comic Sans MS ;color:white;">Follow us on</h4>
	<div id="icons">
		<a class="fa fa-facebook"></a>
		<a class="fa fa-twitter"></a>
		<a class="fa fa-instagram"></a>
	</div>
	<h6 style="margin-left:635px;margin-top:12px;color:yellow;">copyright &copy;Erpsystem</h6>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <%=link_to image_tag("logo/logof.png",width:"250px",height:"50px"),root_path %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">


      

        <!--This is for Login in application-->

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Login
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Student Login',"/student/login",class:"dropdown-item" %>
            <%= link_to 'Faculty Login',"/faculty/login",class:"dropdown-item" %>
          </div>
        </li>
        
        <!--This is for Admin in application-->
        <%= link_to 'Administrator',admin_session_path,
        class:"navbar-brand" %>
<!-- This is for about -->

  <%= link_to 'About-Us',home_about_path,
  class:"navbar-brand" %>



    </ul>
  </div>
</nav>

app/views/home/about.html.erb
<section id="about">
		<div class="about-wrapper container">
			<div class="about-text">
				<p class="small">About Us</p>
				<h2>We have tried to provide the facilities of the student to they can accsess their data easily</h2>
				<p>Indore is a city in west-central India. It’s known for the 7-story Rajwada Palace and the Lal Baag Palace, which date back to Indore’s 19th-century Holkar dynasty. The Holkar rulers are honored by a cluster of tombs and cenotaphs at Chhatri Baag.
				</p>
			</div>
			<div  class="about-img">
				<%= image_tag("background/school.jpg")%>
			</div>
		</div>
	</section>

app/views/home/index.html.erb
<% if admin_signed_in? %>
<div id="fixfooter">
<div id="admindashboard" style="border-style:inset;margin-top:50px;padding-right:2px;padding-left:2px;padding-bottom:120px;">
	<table class="table">
		<thead class="thead-dark">
			<tr>
				<th scope="col">
					<%= link_to 'Register Student',new_student_path,style:"font-size:21px;color:#FFFFFF;text-decoration: none;"%>
				</th>
				<th scope="col">
					<%= link_to 'Register Faculty',new_faculty_path,style:"font-size:21px;color:#FFFFFF;text-decoration: none;"%>
				</th>
				<th scope="col">
					<%= link_to 'Faculties',faculties_path,style:"font-size:21px;color:#FFFFFF;text-decoration: none;"%>
				</th>
				<th scope="col">
					<%= link_to 'Students',students_path,style: "font-size:21px;color:#FFFFFF;text-decoration: none;"  %>
				</th>
				<th scope="col">
					<%= link_to 'Results',home_result_path ,style: "font-size:21px;color:#FFFFFF;text-decoration: none;" %>
				</th>
				<th scope="col">
					<%= link_to 'Edit-Profile',edit_admin_registration_path ,style: "font-size:21px;color:#FFFFFF;text-decoration: none;" %>
				</th>
				<th scope="col">
					<%= link_to 'Sign-out',destroy_admin_session_path,method: :delete, class:"navbar-brand",style: "font-size:21px;color:#FFFFFF;text-decoration:none;" %>
				</th>
			</tr>
		</thead>
	</table>

	<br><br>
	<h5 style="color: red;margin-left:40px;">Hello, <%= current_admin.name %></h5>
	<h4 style="margin-left:40px">Wel-come in Admin Dashboard</h4>
	<br>
	<br><br><br><br><br><br>
</div>
</div>
<% else %>
<div id="homepage">
			<br> <br><br><br>
			<h1 id="heading">Welcome in ERP portal</h1>

</div>
<% end %>

app/views/home/result.html.erb
<% if admin_signed_in? %>
<html>
   <head>
   </head>
  <body >
      <h1 align="center">Results</h1>
      <br>
  <div style="border-style:inset;margin-top:5px;padding-right:1px;padding-left:1px;padding-bottom:120px;">
    <table class="table table-striped table-bordered table-hover">
      <thead class="thead-dark">
        <tr>
          <th align="center">Roll No.</th>
          <th align="center">Hindi</th>
          <th align="center">English</th>
          <th align="center">Maths</th>
          <th align="center">Science</th>
          <th align="center">Social Science</th>
          <th align="center">Total Marks</th>
          <th align="center">Obtained Marks</th>
          <th align="center">Result</th>
        </tr>
      </thead>

      <tbody>
        <% @result.each do |s| %>
          <tr>
            <td align="center"><%= s.student_roll%></td>
            <td align="center"><%= s.hindi%></td>
            <td align="center"><%= s.english%></td>
            <td align="center"><%= s.maths%></td>
            <td align="center"><%= s.science%></td>
            <td align="center"><%= s.social_science%></td>
            <td align="center"><%= s.total%></td>
            <td align="center"><%= s.obtained_marks%></td>
            <td align="center"><%= s.remark%></td>
          </tr>
        <% end %>
      </tbody>
      </table>
    </div>
    <br>
    <h4>Actions:

    <td align="center"><%= link_to 'Preview Result',result_check_marks_path ,class:"btn btn-dark"%></td>


    <td align="center"><%= link_to 'Publish Result',result_publish_path ,class:"btn btn-dark"%></td>

    </h4>
<br>
<br>
<%= link_to 'Back', root_path %>
<br>
    <% else %>
      <div id="homepage">
        <br> <br><br><br>
        <h1 id="heading">Welcome in ERP portal</h1>
        <br><br>
        <h1 style="margin-left:130px;color:red;">Error,404</h1>
        <h2 style="margin-left:130px;color:red;">Page Not Found</h2>
      </div>
    <% end %>
</body>
</html>